title: Bulk Delete Tags
description: This Add-On allows you to clear all tags or a specific key/value pair from a set of documents. If you select _tag, it will delete all tags on the document. 
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  del_key:
    title: Key name of metadata you want to remove. 
    type: string
    description: If _tag is selected, you must specify a value of tag you'd like deleted or leave it blank and select clear all. You may provide a key name here instead.
    default: _tag 
  del_value:
    title: Value of the tag that you would like removed. 
    type: string
    description: Only works if _tag is provided as the key name. 
  clear_all:
    title: Clear all tags?
    type: boolean
    description: Only works if _tag is provided as the key name and no value is specified.
categories: 
  - bulk
