title: Bulk Delete Tags
description: This Add-On allows you to clear all tags or a specific key/value pair from a set of documents. If you select _tag, it will delete all tags on the document. 
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  del_key:
    title: Key name of metadata you want to remove. 
    type: string
    description: If _tag is selected, all tags be deleted. Otherwise, if you provide a key only the metadata under that key will be removed. 
    default: _tag 
categories: 
  - bulk
