title: Bulk Delete Tags
description: This Add-On allows you to clear all tags or a specific key/value pair from a set of documents. 
instruction: "If you select _tag, you must either provide a tag value that you would like cleared or select clear_all and leave value empty. If you provide a key name instead, those keys will be removed."
type: object
documents:
  - selected
  - query
properties:
  del_key:
    title: Key name of metadata you want to remove. 
    type: string
  del_value:
    title: Value of the tag that you would like removed. 
    type: string
    description: Only works if _tag is provided as the key name. 
  clear_all:
    title: Clear all tags?
    type: boolean
    description: Only works if _tag is provided as the key name and no value is specified.
categories: 
  - bulk
